In [ ]:
import pandas as pd
scores = pd.Series([90,85,67], index=['amir', 'sara', 'noha'])
print(scores)

amir    90
sara    85
noha    67
dtype: int64

In [ ]:
data = {
    "name": ["Amir", "Sara", "Leo"],
    "quiz1": [90, 70, 82],
    "quiz2": [85, 60, 77],
}
df = pd.DataFrame(data)
print(df)

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60
2   Leo     82     77

In [ ]:
# fields  or columns
# records or rows

In [ ]:
print(df.shape)

(3, 3)

In [ ]:
print(df.columns)

Index(['name', 'quiz1', 'quiz2'], dtype='object')

In [ ]:
print(df.dtypes)

name     object
quiz1     int64
quiz2     int64
dtype: object

In [ ]:
df.head(2)

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60

In [ ]:
df.describe()

           quiz1      quiz2
count   3.000000   3.000000
mean   80.666667  74.000000
std    10.066446  12.767145
min    70.000000  60.000000
25%    76.000000  68.500000
50%    82.000000  77.000000
75%    86.000000  81.000000
max    90.000000  85.000000

In [ ]:
print(df['quiz1'])

0    90
1    70
2    82
Name: quiz1, dtype: int64

In [ ]:
print(df['name'])

0    Amir
1    Sara
2     Leo
Name: name, dtype: object

In [ ]:
print(df[['name' , 'quiz1','quiz2']])

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60
2   Leo     82     77

In [ ]:
df = df.set_index('name')
print(df)

      quiz1  quiz2  average  passed
name
Amir     90   85.0     87.5    True
Sara     70    NaN     65.0   False
Leo      82   77.0     79.5    True

In [ ]:
df

   name  quiz1  quiz2  average  passed
0  Amir     90   85.0     87.5    True
1  Sara     70    NaN     65.0   False
2   Leo     82   77.0     79.5    True

In [ ]:
print(df.loc['Sara'])

quiz1         70
quiz2        NaN
average     65.0
passed     False
Name: Sara, dtype: object

In [ ]:
print(df.iloc[1])

quiz1         70
quiz2        NaN
average     65.0
passed     False
Name: Sara, dtype: object

In [ ]:
df.head()

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60
2   Leo     82     77

In [ ]:
passed = df[df['quiz1'] >= 80]
print(passed)

   name  quiz1  quiz2
0  Amir     90     85
2   Leo     82     77

In [ ]:
df.head()

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60
2   Leo     82     77

In [ ]:
print(df[df['quiz2'] <=80])

   name  quiz1  quiz2
1  Sara     70     60
2   Leo     82     77

In [ ]:
both = df[(df["quiz1"] >= 80) | (df["quiz2"] >= 80)]
print(both)

   name  quiz1  quiz2
0  Amir     90     85
2   Leo     82     77

In [ ]:
print(1 and 0)

0

In [ ]:
print(1 or 1)

1

In [ ]:
print(df.sort_values("quiz1"))  # smallest quiz1 first
print(df.sort_values("quiz1", ascending=False))  # largest first

   name  quiz1  quiz2
1  Sara     70     60
2   Leo     82     77
0  Amir     90     85
   name  quiz1  quiz2
0  Amir     90     85
2   Leo     82     77
1  Sara     70     60

In [ ]:
df.head()

   name  quiz1  quiz2
0  Amir     90     85
1  Sara     70     60
2   Leo     82     77

In [ ]:
df['average'] = (df['quiz1'] + df['quiz2']) / 2
print(df)

   name  quiz1  quiz2  average
0  Amir     90     85     87.5
1  Sara     70     60     65.0
2   Leo     82     77     79.5

In [ ]:
df['passed'] = df['average']>= 70
print(df)
print("-----------------")
print(df[["name", "average", "passed"]])

   name  quiz1  quiz2  average  passed
0  Amir     90     85     87.5    True
1  Sara     70     60     65.0   False
2   Leo     82     77     79.5    True
-----------------
   name  average  passed
0  Amir     87.5    True
1  Sara     65.0   False
2   Leo     79.5    True

In [ ]:
import numpy as np
df.loc[1,'quiz2']= np.nan

In [ ]:
df

   name  quiz1  quiz2  average  passed
0  Amir     90   85.0     87.5    True
1  Sara     70    NaN     65.0   False
2   Leo     82   77.0     79.5    True

In [ ]:
print(df.isna())

    name  quiz1  quiz2  average  passed
0  False  False  False    False   False
1  False  False   True    False   False
2  False  False  False    False   False

In [ ]:
print(df['quiz2'].isna().sum())

1

In [ ]:
filled =df.fillna(65)
print(filled)

   name group  score
0  Amir     A     90
1  Sara     B     70
2   Leo     A     82
3  Nina     B     60

In [ ]:
import numpy as np
df.loc[1,'quiz2']= np.nan

In [ ]:
dropped = df.dropna()
print(dropped)

   name  quiz1  quiz2  average  passed
0  Amir     90   85.0     87.5    True
2   Leo     82   77.0     79.5    True

In [ ]:
data = {
"name": ["Amir", "Sara", "Leo", "Nina"],
"group": ["A", "B", "A", "B"],
"score": [90, 70, 82, 60],
}
df = pd.DataFrame(data)
print(df.groupby("group")['score'].mean())

group
A    86.0
B    65.0
Name: score, dtype: float64

In [ ]:
print(df.groupby("group")["score"].count())

group
A    2
B    2
Name: score, dtype: int64

In [ ]:
print(df.groupby("group")["score"].max())

group
A    90
B    70
Name: score, dtype: int64

In [ ]:
print(df.groupby("group")["score"].min())

group
A    82
B    60
Name: score, dtype: int64

In [ ]:
print(df.groupby("group")["score"].agg(["mean", "max", "count"]))

       mean  max  count
group
A      86.0   90      2
B      65.0   70      2

In [ ]:
df = pd.DataFrame({"x": [1, 2, 3]})
df["y"] = df["x"] * 10
print(df["y"].tolist())
print(df["y"])

[10, 20, 30]
0    10
1    20
2    30
Name: y, dtype: int64

In [ ]:
df.head()

   x   y
0  1  10
1  2  20
2  3  30